import Head from 'next/head'
import Image from 'next/image'
import { PageLayout } from '../components/layout/PageLayout'
import { Home } from '../components/organisms/Home'
import styles from '../styles/Home.module.css'

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <PageLayout>
        <Home />
      </PageLayout>
    </>
  )
}
